In [1]:
import numpy as np

In [2]:
# ES1
matrice = np.random.randint(0, 10, (4,5))
matrice

array([[1, 6, 1, 9, 3],
       [4, 1, 3, 3, 7],
       [6, 8, 1, 2, 2],
       [6, 5, 0, 7, 6]], dtype=int32)

In [ ]:
#Se si ha un insieme S di valori S = {x1, x2, x3, x4, x5...}, m = x1, x2, x3, x4, x5 / N (Si può anche scrivere con il simbolo della sommatoria)
#l'idea della deviazione standard è andare a calcolare quanto il valore dista dalla media -> x1 - m (Residuo), quanto un valore dista dalla media
#Si considera il residuo al quadrato, il modulo. (x1 - m)^2 => A questo punto si definisce V che è la media degli scarti quadratici (V -> Varianza è un numero)
#La deviazione è uguale alla radice della varianza
#In numpy si fa con np.std()
#La media invece si fa con np.mean()

In [28]:
# ES2
matrice2 = np.random.randint(-10, 11, (6,6)) #estremi inclusi, sinistro sempre incluso, destro no
matrice2

array([[  3,   3,   3,  -2,  -9,   8],
       [  1,  -8,  -8,  -3,  -1,  -5],
       [ -8, -10,  10,   1,  -1,  -7],
       [  7,   9,  -7,   9,  -2,  -7],
       [  3,   2,  -4,   5,  -5,  -4],
       [ -8, -10,   2,   7,  -8, -10]], dtype=int32)

In [29]:
matrice_negativi = matrice2 < 0
matrice_negativi #matrice booleana

array([[False, False, False,  True,  True, False],
       [False,  True,  True,  True,  True,  True],
       [ True,  True, False, False,  True,  True],
       [False, False,  True, False,  True,  True],
       [False, False,  True, False,  True,  True],
       [ True,  True, False, False,  True,  True]])

In [30]:
matrice2[matrice_negativi] = 0
matrice2

array([[ 3,  3,  3,  0,  0,  8],
       [ 1,  0,  0,  0,  0,  0],
       [ 0,  0, 10,  1,  0,  0],
       [ 7,  9,  0,  9,  0,  0],
       [ 3,  2,  0,  5,  0,  0],
       [ 0,  0,  2,  7,  0,  0]], dtype=int32)

In [39]:
somma_righe = np.sum(matrice2, axis=1) #Asse 0 = colonne Asse 1 = righe
somma_righe

array([17,  1, 11, 25, 10,  9])

In [40]:
solo_maggiori = somma_righe > 15
matrice2[solo_maggiori]

array([[3, 3, 3, 0, 0, 8],
       [7, 9, 0, 9, 0, 0]], dtype=int32)

In [75]:
#Es3
array = np.random.uniform(-5., 35.,(100))
array

array([32.19412937, 20.90758824,  0.32301336, 32.65958041, 21.08413311,
       27.57243422,  4.08807777, 25.38291695, 15.74361696, -2.34068621,
       21.49897365, 18.50958436, 13.54418452, 25.69952235, 14.09163922,
       17.85451169, 18.82845673, 12.16631153,  1.12222231, 16.68506592,
       13.6408282 , 20.59622531, -2.13935496, 25.11487949,  6.61140664,
        7.30469745, -3.54802228, 16.08477057, 29.42854241, 34.77391475,
       11.30851309,  4.2108899 ,  2.59526769, 14.94474977, 28.37079199,
       16.90324052, 19.13889254, -2.33256055,  8.30061101,  5.10949449,
       22.82358688, 17.73510365, 21.6764918 , 19.75095709, 13.86150158,
       32.79912761, -3.77841844, 34.25974361, 31.50199237,  4.1045971 ,
       14.55532643, 19.08225999, 18.8707998 ,  7.74751804, -0.50910168,
       27.72917752,  3.18335937, 27.15407044, 21.07220204, -3.52724485,
       19.74213953, 34.73111424, 28.19852198, 20.62875401, 20.85987639,
       21.88334784, 31.2323365 ,  7.33562674, -2.99132368, 34.00

In [76]:
giorni1 = array > 15
giorni2 = array < 25
giorni1
giorni2

array([False,  True,  True, False,  True, False,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True, False, False,  True,  True,  True,  True,  True,
        True, False,  True, False,  True,  True,  True, False, False,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
        True, False,  True,  True,  True, False,  True, False,  True,
       False, False,  True, False, False, False,  True,  True,  True,
        True])

In [77]:
giorniFinale = (giorni1)&(giorni2)
giorniFinale

array([False,  True, False, False,  True, False, False, False,  True,
       False,  True,  True, False, False, False,  True,  True, False,
       False,  True, False,  True, False, False, False, False, False,
        True, False, False, False, False, False, False, False,  True,
        True, False, False, False,  True,  True,  True,  True, False,
       False, False, False, False, False, False,  True,  True, False,
       False, False, False, False,  True, False,  True, False, False,
        True,  True,  True, False, False, False, False,  True,  True,
       False, False,  True, False, False,  True, False, False, False,
       False, False, False,  True, False, False, False, False,  True,
       False, False, False, False, False, False,  True,  True, False,
       False])

In [78]:
array[giorniFinale]

array([20.90758824, 21.08413311, 15.74361696, 21.49897365, 18.50958436,
       17.85451169, 18.82845673, 16.68506592, 20.59622531, 16.08477057,
       16.90324052, 19.13889254, 22.82358688, 17.73510365, 21.6764918 ,
       19.75095709, 19.08225999, 18.8707998 , 21.07220204, 19.74213953,
       20.62875401, 20.85987639, 21.88334784, 18.60123694, 17.05279379,
       19.43064327, 23.87819832, 23.71082459, 21.46203333, 23.52238915,
       18.00870249])

In [79]:
np.count_nonzero(array[giorniFinale])

31

In [80]:
array = np.random.uniform(-5., 35.,(100))
array

array([ 2.84855627,  9.51605122,  6.59829707, 12.47113216, 21.65980501,
       15.46592481, 23.09175862,  3.07026713, 20.57656135,  7.0265931 ,
       17.1822264 , 25.12302417, 31.52303234, -4.05726303, 34.930857  ,
       33.24541086,  6.18555058,  5.1554104 , 33.01617587, 15.38787176,
       12.08931009, 23.42767973, 18.30032989, 24.53994092, 11.04548017,
       25.3784491 , 27.74933   , 28.52159294, -4.33539269, 26.6312417 ,
        9.86703991,  7.07622653, -3.5442424 , 19.90945875, 32.9253251 ,
       29.98879866, -3.26371732,  3.30493365,  3.8066909 , -3.17416314,
        3.22000478, 32.46920918,  7.275895  , 27.39491335, 28.60103219,
       34.01052907, 12.40499653, 21.46900062, 33.34332497, 24.11573784,
       -3.62884064, 14.16825251,  4.61643932,  7.9885114 , 17.92561177,
        6.08797193, -2.16268168,  8.87124369, 11.75509349, 19.66045006,
       19.90820797, 14.94785377, 25.70352578, 32.48430393, 29.23118281,
       18.70902563,  0.42378308, 17.26495801, 27.3205068 , -3.71

In [81]:
sotto_zero = array < 0
array[sotto_zero] = 0

sopra_trenta = array > 30
array[sopra_trenta] = 30

array

array([ 2.84855627,  9.51605122,  6.59829707, 12.47113216, 21.65980501,
       15.46592481, 23.09175862,  3.07026713, 20.57656135,  7.0265931 ,
       17.1822264 , 25.12302417, 30.        ,  0.        , 30.        ,
       30.        ,  6.18555058,  5.1554104 , 30.        , 15.38787176,
       12.08931009, 23.42767973, 18.30032989, 24.53994092, 11.04548017,
       25.3784491 , 27.74933   , 28.52159294,  0.        , 26.6312417 ,
        9.86703991,  7.07622653,  0.        , 19.90945875, 30.        ,
       29.98879866,  0.        ,  3.30493365,  3.8066909 ,  0.        ,
        3.22000478, 30.        ,  7.275895  , 27.39491335, 28.60103219,
       30.        , 12.40499653, 21.46900062, 30.        , 24.11573784,
        0.        , 14.16825251,  4.61643932,  7.9885114 , 17.92561177,
        6.08797193,  0.        ,  8.87124369, 11.75509349, 19.66045006,
       19.90820797, 14.94785377, 25.70352578, 30.        , 29.23118281,
       18.70902563,  0.42378308, 17.26495801, 27.3205068 ,  0.  