In [3]:
import numpy as np

#100 punti nel piano
points = np.random.randint(1, 20, (100, 2))

#distanza dall’origine, formula: √(x² + y²)
distances = np.sqrt(np.sum(points**2, axis=1))

distances 

array([20.24845673, 19.79898987, 17.4642492 ,  3.60555128, 11.18033989,
       21.26029163,  9.21954446, 23.02172887, 21.09502311, 25.49509757,
       10.77032961, 17.49285568,  5.65685425, 20.61552813, 17.4642492 ,
       19.84943324, 17.4642492 , 19.84943324, 10.04987562, 17.69180601,
       13.45362405, 15.8113883 , 19.02629759, 20.24845673,  6.08276253,
       19.41648784, 19.41648784,  4.47213595, 11.04536102, 17.11724277,
       20.59126028, 13.60147051, 17.80449381, 12.16552506, 16.1245155 ,
       17.72004515, 16.4924225 , 12.36931688, 12.72792206, 19.23538406,
       23.43074903, 17.02938637, 10.44030651, 14.03566885, 13.41640786,
       12.04159458,  8.06225775, 14.4222051 ,  4.47213595, 18.02775638,
        1.41421356, 11.04536102, 15.8113883 , 16.2788206 , 16.2788206 ,
       19.79898987, 17.2626765 , 19.10497317,  4.24264069, 19.23538406,
       15.65247584, 25.49509757,  6.08276253, 24.8394847 , 24.75883681,
       14.86606875, 18.97366596, 17.2626765 , 19.10497317, 11.70

In [20]:
import numpy as np

R, C = 6, 6   #dimensione matrice
p = 8         #elementi da inserire

M = np.zeros((R, C))

#estraggo p posizioni distinte
idx = np.random.choice(R * C, p, replace=False)

#trasformo gli indici in (riga, colonna)
rows = idx // C
cols = idx % C

#assegno i valori
M[rows, cols] = 1
print(M)

[[0. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]
