In [1]:
#Esercizio lancio di dadi, 1000 lanci di due dadi a sei facce
#Usare una matrice, non due array
#Quante volte la somma dei due dadi è esattamente 7?
#Quante volte i due dadi mostrano lo stesso valore?
#Media del punteggio ottenuto
#moda delle somma (Il valore che appare con la maggiore frequenza)

In [17]:
import numpy as np

N_LANCI = 1000
N_DADI = 2
N_FACCE = 6

matrice_dadi = np.random.randint(1, N_FACCE + 1, (N_DADI, N_LANCI))
print(matrice_dadi)

[[3 5 2 ... 6 5 1]
 [5 6 2 ... 5 1 2]]


In [18]:
#Indicizzazione booleana per trovare il numero dei 7
matrice_temporanea = matrice_dadi[0] + matrice_dadi[1] == 7
numeri_volte_7 = np.count_nonzero(matrice_temporanea)
print(numeri_volte_7)

170


In [19]:
#Stessa cosa per valori uguali
matrice_temporanea = matrice_dadi[0] == matrice_dadi[1]
#print(matrice_temporanea)
numero_volte_stesso_valore = np.count_nonzero(matrice_temporanea)
print(numero_volte_stesso_valore)

135


In [52]:
#Media del punteggio ottenuto TOTALE
punteggio_temporaneo = np.sum(matrice_dadi)
#print(punteggio_temporaneo)
media = punteggio_temporaneo / N_LANCI
print(media)

#metodo_veloce per medie totale
somme = np.sum(matrice_dadi, axis = 0)
medie = np.mean(somme)
print(medie)

#Media del punteggio per ogni soma
punteggio_somme = matrice_dadi[0] + matrice_dadi[1]
medie = punteggio_somme / N_DADI
print(medie)

7.098
7.098
[4.  5.5 2.  5.  4.5 3.5 3.5 2.  2.5 4.5 2.5 4.5 5.5 2.  6.  2.5 3.  3.5
 4.5 6.  3.5 5.5 5.  2.  4.5 4.  3.5 3.5 4.5 4.  2.5 1.5 4.  5.  5.  2.5
 4.  4.  3.  2.  1.5 4.5 1.5 3.5 4.  5.5 5.5 3.5 3.  3.5 3.5 1.  1.  5.
 5.5 4.  5.5 2.5 2.  4.  3.5 2.5 3.5 2.5 2.  4.  4.5 3.  5.  3.5 1.5 5.
 5.5 4.5 3.5 3.  6.  4.5 3.5 3.5 2.  4.5 3.5 5.5 3.5 4.  3.5 2.  4.  2.5
 3.  2.  2.5 2.  4.5 2.5 3.5 4.  2.  2.5 5.5 2.5 2.  4.  5.  5.  3.  3.5
 2.5 3.  6.  3.  4.  3.5 2.5 5.  2.5 3.5 4.  3.5 5.  5.  4.5 5.  3.  4.5
 1.  3.  4.  2.5 2.  2.  3.  3.5 3.5 5.  3.5 5.  6.  4.  3.5 4.  5.  5.
 3.5 4.5 1.5 3.5 4.  3.  4.5 4.  2.5 2.5 2.  3.  3.  1.5 3.5 3.5 1.5 3.
 1.  4.  4.  4.  4.  4.5 3.5 1.  5.  3.5 3.5 3.  2.5 3.5 2.5 3.5 2.5 4.5
 1.5 4.  6.  3.5 3.5 1.5 4.5 1.  1.  4.  5.  3.5 4.5 2.5 3.  2.  4.  3.5
 1.5 3.5 2.5 5.  4.  5.  5.  2.5 2.5 4.  2.5 3.5 3.5 3.5 6.  5.5 4.5 2.5
 6.  5.5 5.  4.  3.  5.5 3.  3.  5.  3.5 4.5 3.5 2.5 2.5 3.  2.5 2.5 3.
 3.  3.  4.  4.  1.  2.5 5.  5.5 2.5 2.  3. 

In [53]:
#Moda delle somme
matrice_temporanea = matrice_dadi[0] + matrice_dadi[1]
print(matrice_temporanea)
moda_somme = np.argmax(np.bincount(matrice_temporanea))
print(np.bincount(matrice_temporanea)) #mi conta quante volte esce quella somma
print(moda_somme) #è per forza 7

[ 8 11  4 10  9  7  7  4  5  9  5  9 11  4 12  5  6  7  9 12  7 11 10  4
  9  8  7  7  9  8  5  3  8 10 10  5  8  8  6  4  3  9  3  7  8 11 11  7
  6  7  7  2  2 10 11  8 11  5  4  8  7  5  7  5  4  8  9  6 10  7  3 10
 11  9  7  6 12  9  7  7  4  9  7 11  7  8  7  4  8  5  6  4  5  4  9  5
  7  8  4  5 11  5  4  8 10 10  6  7  5  6 12  6  8  7  5 10  5  7  8  7
 10 10  9 10  6  9  2  6  8  5  4  4  6  7  7 10  7 10 12  8  7  8 10 10
  7  9  3  7  8  6  9  8  5  5  4  6  6  3  7  7  3  6  2  8  8  8  8  9
  7  2 10  7  7  6  5  7  5  7  5  9  3  8 12  7  7  3  9  2  2  8 10  7
  9  5  6  4  8  7  3  7  5 10  8 10 10  5  5  8  5  7  7  7 12 11  9  5
 12 11 10  8  6 11  6  6 10  7  9  7  5  5  6  5  5  6  6  6  8  8  2  5
 10 11  5  4  6  4  7  9  6  8  9 10 10 11 11  5  4  5  9  8  3  6  2  7
  8  3  7 11  7 12  9 11 11  2  6 10  7  5  8  6  4  8  9  8  2  6  9  7
  7  7  3  2  8  6  5  7  2  6  3  6  6  3  6  9  7  5 10  6  7  9  6  4
  8 10  6  8 10  6  6 11 11 11  6  7  3  5  6  3  3

In [46]:
#Se voglio una matrice 2*1000 come una 1000*2 basta fare così
matrice_dadi.T

array([[3, 5],
       [5, 6],
       [2, 2],
       ...,
       [6, 5],
       [5, 1],
       [1, 2]], dtype=int32)

In [54]:
import matplotlib.pyplot as plt
ax, fig = plt.subplots(figsize = (3, 3))
ax.bar([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]moda_somme)
plt.show()

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1278309060.py, line 3)